# Generated by Django 5.2.6 on 2025-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email'], name='account_otp_email_2aadfc_idx'),
        ),
    ]
